import { ensureEnv } from '@o/helpers'

if (typeof window !== 'undefined') {
  throw new Error(`This is a server-only file`)
}

// 🔒 start - this is generated by "bun env:update"
export const BETTER_AUTH_SECRET = ensureEnv('BETTER_AUTH_SECRET')
export const BETTER_AUTH_URL = ensureEnv('BETTER_AUTH_URL')
export const ONE_SERVER_URL = ensureEnv('ONE_SERVER_URL')
export const VITE_ZERO_HOSTNAME = ensureEnv('VITE_ZERO_HOSTNAME', "")
export const VITE_WEB_HOSTNAME = ensureEnv('VITE_WEB_HOSTNAME', "")
export const ZERO_VERSION = ensureEnv('ZERO_VERSION')
export const ZERO_NUM_SYNC_WORKERS = ensureEnv('ZERO_NUM_SYNC_WORKERS', "2")
export const ZERO_CVR_MAX_CONNS = ensureEnv('ZERO_CVR_MAX_CONNS', "4")
export const ZERO_UPSTREAM_MAX_CONNS = ensureEnv('ZERO_UPSTREAM_MAX_CONNS', "8")
export const ZERO_PER_USER_MUTATION_LIMIT_MAX = ensureEnv('ZERO_PER_USER_MUTATION_LIMIT_MAX', "30")
export const ZERO_PER_USER_MUTATION_LIMIT_WINDOW_MS = ensureEnv('ZERO_PER_USER_MUTATION_LIMIT_WINDOW_MS', "60000")
export const ZERO_MUTATE_FORWARD_COOKIES = ensureEnv('ZERO_MUTATE_FORWARD_COOKIES', "true")
export const ZERO_QUERY_FORWARD_COOKIES = ensureEnv('ZERO_QUERY_FORWARD_COOKIES', "true")
export const ZERO_APP_PUBLICATIONS = ensureEnv('ZERO_APP_PUBLICATIONS', "zero_takeout")
// 🔒 end - this is generated by "bun env:update"

// database urls set conditionally based on deployment
// use bracket notation to prevent build-time inlining
export const ZERO_UPSTREAM_DB = process.env['ZERO_UPSTREAM_DB'] || ''
export const ZERO_CVR_DB = process.env['ZERO_CVR_DB'] || ''
export const ZERO_CHANGE_DB = process.env['ZERO_CHANGE_DB'] || ''
